CREATE TABLE `employee` (
  `id` int NOT NULL,
  `first_name` varchar(255) DEFAULT NULL,
  `last_name` varchar(255) DEFAULT NULL,
  `salary` varchar(255) DEFAULT NULL,
  `dob` Date DEFAULT NULL,
  `graduation` tinyblob,
  `dept_id` int DEFAULT NULL,
  `gender` varchar(255) DEFAULT NULL,
  `team_id` int DEFAULT NULL,
  `manger_id` int DEFAULT NULL,
  `emp_id` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKaqchbcb8i6nvtl9g6c72yba0p` (`dept_id`),
  KEY `FK8d7lrsr6kwirr93rx0tafnoqa` (`team_id`),
  KEY `FKamaod4x10sugobqo9glua0poa` (`manger_id`),
  KEY `FKbpyf0uah1j1au5w209mj5k2hh` (`emp_id`),
  CONSTRAINT `FK8d7lrsr6kwirr93rx0tafnoqa` FOREIGN KEY (`team_id`) REFERENCES `team` (`id`),
  CONSTRAINT `FKamaod4x10sugobqo9glua0poa` FOREIGN KEY (`manger_id`) REFERENCES `employee` (`id`),
  CONSTRAINT `FKaqchbcb8i6nvtl9g6c72yba0p` FOREIGN KEY (`dept_id`) REFERENCES `department` (`id`),
  CONSTRAINT `FKbpyf0uah1j1au5w209mj5k2hh` FOREIGN KEY (`emp_id`) REFERENCES `team` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
